title = "Redis Configs"

[[default.master]]
	addr = "localhost:6379"
	password = ""
	db = 0
[[default.slave]]
	addr = "localhost:6379"
    password = ""
    db = 0
[[default.slave]]
	addr = "localhost:6379"
    password = ""
    db = 0

[[crm.master]]
	addr = "localhost:6379"
	password = ""
	db = 0
[[crm.slave]]
	addr = "localhost:6379"
    password = ""
    db = 0
[[crm.slave]]
	addr = "localhost:6379"
    password = ""
    db = 0